// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twvjbdvkileunbaoysyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dmpiZHZraWxldW5iYW95c3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMTg2ODQsImV4cCI6MjA0OTc5NDY4NH0.s4VfdZRZ66qyqGf9ZFUWA8nBwGp7TaPL5lIdKz0WpCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);