// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhsslrlujuirbclcbrmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoc3Nscmx1anVpcmJjbGNicm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NjI1MjgsImV4cCI6MjA0OTEzODUyOH0.jVmG1fGf6TeuxKueaXPGZrJTcf6KqF-ZLUj3ynbdBUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);